name: main-workflow

env:
  IMAGE_REPOSITORY: nidhinmetocean/foobar

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  # Run all the unit tests
  run-tests:
    runs-on: ubuntu-latest
    steps:
      # checkout the source code
      - name: Checkout source code
        uses: actions/checkout@v2

      # install go
      - name: Install Go lang
        uses: actions/setup-go@v2-beta
        with:
          go-version: "^1.14"

      # print go version
      - name: Print Go version
        run: go version

      # run unit tests
      - name: Run unit tests
        run: go test -v ./...

  build-and-release:
    runs-on: ubuntu-latest
    steps:
      # Check out source code.
      - name: Check out source code
        uses: actions/checkout@v2

      # Build and push container image.
      - name: Build and push container image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ env.IMAGE_REPOSITORY }}
          tag_with_ref: true
          tag_with_sha: true
  